# Generated by Django 4.1.1 on 2022-10-15 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_number",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("class_grade", models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AddEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=25)),
                ("mobile", models.IntegerField()),
                ("emp_type", models.CharField(max_length=25)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/employee"
                    ),
                ),
                ("joining_date", models.DateField(null=True)),
                ("salary", models.IntegerField()),
                ("father_name", models.CharField(blank=True, max_length=25, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("experience", models.CharField(max_length=25)),
                ("religion", models.CharField(blank=True, max_length=25, null=True)),
                ("cast", models.CharField(blank=True, max_length=25, null=True)),
                ("email", models.EmailField(max_length=50)),
                ("Address", models.TextField(max_length=300)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "username",
                    models.CharField(default=myadmin.models.name_gen, max_length=15),
                ),
                (
                    "password",
                    models.CharField(default=myadmin.models.pass_gen, max_length=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=25)),
                (
                    "reg_number",
                    models.IntegerField(default=myadmin.models.random_reg_id),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=3500,
                        null=True,
                        upload_to="photos/student",
                    ),
                ),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(max_length=15, null=True)),
                ("mobile", models.IntegerField()),
                ("Address", models.TextField(max_length=300)),
                ("email", models.EmailField(max_length=50)),
                ("country", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=25)),
                ("city", models.CharField(max_length=25)),
                ("pincode", models.IntegerField()),
                (
                    "username",
                    models.CharField(default=myadmin.models.name_gen, max_length=15),
                ),
                (
                    "password",
                    models.CharField(default=myadmin.models.pass_gen, max_length=15),
                ),
                ("father", models.CharField(blank=True, max_length=25, null=True)),
                ("mother", models.CharField(blank=True, max_length=25, null=True)),
                ("father_id", models.CharField(blank=True, max_length=25, null=True)),
                ("mother_id", models.CharField(blank=True, max_length=25, null=True)),
                ("father_job", models.CharField(blank=True, max_length=25, null=True)),
                ("mother_job", models.CharField(blank=True, max_length=25, null=True)),
                ("father_mob", models.IntegerField()),
                ("mother_mob", models.IntegerField()),
                (
                    "class_number",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.IntegerField(blank=True, null=True)),
                ("post_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/teachers"
                    ),
                ),
                ("join_date", models.DateField(blank=True, null=True)),
                ("salary", models.IntegerField(blank=True, null=True)),
                ("experience", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=50, null=True, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, max_length=300, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "accounts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myadmin.addclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("present", models.BooleanField()),
                ("leave", models.BooleanField()),
                ("absent", models.BooleanField()),
                ("holiday", models.BooleanField()),
                (
                    "class_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addstudent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addstudent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="empAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("present", models.BooleanField()),
                ("leave", models.BooleanField()),
                ("absent", models.BooleanField()),
                ("holiday", models.BooleanField()),
                (
                    "emp_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addemployee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.empattendance",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.studattendance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.IntegerField(blank=True, null=True)),
                (
                    "class_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addclass",
                    ),
                ),
                (
                    "subject_name",
                    models.ManyToManyField(blank=True, to="myadmin.subjectlist"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_name", models.CharField(max_length=25)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "class_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddClassTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addsubject",
                    ),
                ),
            ],
        ),
    ]
