# Generated by Django 4.1.1 on 2022-09-19 12:43

from django.db import migrations, models
import django.db.models.deletion
import myadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('class_grade', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=25)),
                ('mobile', models.IntegerField()),
                ('emp_type', models.CharField(max_length=25)),
                ('image', models.ImageField(null=True, upload_to='photos/employee')),
                ('joining_date', models.DateField(null=True)),
                ('salary', models.IntegerField()),
                ('father_name', models.CharField(max_length=25, null=True)),
                ('gender', models.CharField(choices=[('None', 'Choose Your gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('experience', models.CharField(max_length=25)),
                ('religion', models.CharField(max_length=25, null=True)),
                ('cast', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('Address', models.TextField(max_length=300)),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=25)),
                ('reg_number', models.IntegerField(default=myadmin.models.random_reg_id)),
                ('image', models.ImageField(null=True, upload_to='photos/student')),
                ('admission_date', models.DateField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('None', 'Choose Your gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15, null=True)),
                ('mobile', models.IntegerField()),
                ('Address', models.TextField(max_length=300)),
                ('religion', models.CharField(max_length=25, null=True)),
                ('cast', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addclass')),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=25)),
                ('mother', models.CharField(max_length=25)),
                ('father_id', models.CharField(max_length=25)),
                ('mother_id', models.CharField(max_length=25)),
                ('father_job', models.CharField(max_length=25)),
                ('mother_job', models.CharField(max_length=25)),
                ('father_mob', models.IntegerField()),
                ('mother_mob', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IdCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addstudent')),
            ],
        ),
        migrations.CreateModel(
            name='AddSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=25)),
                ('Marks', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addclass')),
            ],
        ),
        migrations.AddField(
            model_name='addstudent',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.parentinfo'),
        ),
    ]
