# Generated by Django 4.1.1 on 2022-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclass',
            name='class_number',
            field=models.CharField(max_length=5),
        ),
    ]
