# Generated by Django 4.1.1 on 2022-09-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsubject',
            name='grade',
        ),
    ]
