# Generated by Django 4.1.1 on 2022-10-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstudent",
            name="father",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="addstudent",
            name="father_id",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="addstudent",
            name="father_job",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="addstudent",
            name="mother",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="addstudent",
            name="mother_id",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="addstudent",
            name="mother_job",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
