# Generated by Django 4.1.1 on 2022-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_remove_addsubject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsubject',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
