# Generated by Django 4.1.1 on 2022-10-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0002_alter_addstudent_father_alter_addstudent_father_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ParentInfo",
        ),
    ]
