# Generated by Django 4.1.1 on 2022-09-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_alter_addclass_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclass',
            name='class_grade',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
