# Generated by Django 4.1.1 on 2022-11-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0002_remove_day_subjects_day_subject_name_delete_weekdays"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="subject_name",
            new_name="subject",
        ),
    ]
