# Generated by Django 4.1.1 on 2022-11-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0003_rename_subject_name_day_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="day",
            old_name="subject",
            new_name="subject_name",
        ),
    ]
