# Generated by Django 4.1.1 on 2022-10-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0003_alter_addstudent_address_alter_addstudent_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addstudent",
            name="email",
        ),
        migrations.RemoveField(
            model_name="addstudent",
            name="password",
        ),
        migrations.RemoveField(
            model_name="addstudent",
            name="username",
        ),
    ]
