# Generated by Django 4.1.1 on 2022-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_addclass_class_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclass',
            name='class_grade',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='addclass',
            name='class_number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
