# Generated by Django 4.1.1 on 2022-10-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0004_remove_addstudent_email_remove_addstudent_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstudent",
            name="class_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myadmin.addclass",
            ),
        ),
    ]
