# Generated by Django 4.1.1 on 2022-09-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_alter_addclass_class_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('leave', models.BooleanField()),
                ('absent', models.BooleanField()),
                ('holiday', models.BooleanField()),
                ('class_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addstudent')),
            ],
        ),
        migrations.CreateModel(
            name='empAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('leave', models.BooleanField()),
                ('absent', models.BooleanField()),
                ('holiday', models.BooleanField()),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addemployee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.empattendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.studattendance')),
            ],
        ),
        migrations.CreateModel(
            name='AddExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('class_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addclass')),
            ],
        ),
    ]
