# Generated by Django 4.1.1 on 2022-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0004_alter_addstudent_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstudent",
            name="image",
            field=models.ImageField(
                blank=True, max_length=3500, null=True, upload_to="photos/student"
            ),
        ),
    ]
