# Generated by Django 4.1.1 on 2022-09-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_studattendance_empattendance_attendancereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studattendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.addstudent'),
        ),
        migrations.CreateModel(
            name='AddClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addsubject')),
            ],
        ),
    ]
