# Generated by Django 4.1.1 on 2022-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0005_alter_addstudent_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstudent",
            name="admission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="addstudent",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
