# Generated by Django 4.1.1 on 2022-10-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0006_alter_addstudent_admission_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstudent",
            name="gender",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
