# Generated by Django 4.1.1 on 2022-09-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_alter_studattendance_student_addclasstest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclass',
            name='class_number',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
