# Generated by Django 4.1.1 on 2022-10-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0006_addstudent_is_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addstudent",
            name="is_student",
        ),
    ]
