# Generated by Django 4.1.1 on 2022-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_alter_addclass_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclass',
            name='class_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
