# Generated by Django 4.1.1 on 2022-10-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0007_alter_addstudent_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addstudent",
            name="cast",
        ),
        migrations.RemoveField(
            model_name="addstudent",
            name="religion",
        ),
    ]
