# Generated by Django 4.1.1 on 2022-09-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_alter_addclass_class_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addsubject',
            old_name='Marks',
            new_name='marks',
        ),
        migrations.AlterField(
            model_name='addclass',
            name='class_grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
