# Generated by Django 4.1.1 on 2022-10-21 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myadmin", "0009_alter_teacher_class_number_alter_teacher_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addstudent",
            name="student_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentaccount",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
