# Generated by Django 4.1.1 on 2022-10-10 13:09

from django.db import migrations, models
import django.db.models.deletion
import myadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0009_alter_addemployee_cast_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=30)),
                ("mobile", models.IntegerField()),
                ("post_name", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="photos/teachers")),
                ("join_date", models.DateField()),
                ("salary", models.IntegerField()),
                ("experience", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("address", models.TextField(max_length=300)),
                ("date_of_birth", models.DateField()),
                (
                    "username",
                    models.CharField(
                        default=myadmin.models.name_gen, max_length=15, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="addclass",
            name="class_teaacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myadmin.teacher",
            ),
        ),
    ]
