# Generated by Django 4.1.1 on 2022-09-22 04:24

from django.db import migrations, models
import myadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_rename_marks_addsubject_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='password',
            field=models.CharField(default=myadmin.models.pass_gen, max_length=15),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='username',
            field=models.CharField(default=myadmin.models.name_gen, max_length=15),
        ),
    ]
