# Generated by Django 4.1.1 on 2022-10-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0010_teacher_addclass_class_teaacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="address",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="experience",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/teachers"),
        ),
    ]
