# Generated by Django 4.1.1 on 2022-10-10 13:13

from django.db import migrations, models
import myadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0011_alter_teacher_address_alter_teacher_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="password",
            field=models.CharField(default=myadmin.models.pass_gen, max_length=15),
        ),
    ]
