# Generated by Django 4.1.1 on 2022-09-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_addstudent_password_addstudent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/student'),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.parentinfo'),
        ),
    ]
