# Generated by Django 4.1.1 on 2022-10-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0011_alter_addstudent_student_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
