# Generated by Django 4.1.1 on 2022-10-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0012_teacher_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="class_teacher",
        ),
    ]
