# Generated by Django 4.1.1 on 2022-10-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0012_alter_teacher_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addclass",
            old_name="class_teaacher",
            new_name="class_teacher",
        ),
    ]
