# Generated by Django 4.1.1 on 2022-10-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0013_remove_teacher_class_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_name", models.CharField(max_length=15)),
                (
                    "class_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.addclass",
                    ),
                ),
                ("subject_name", models.ManyToManyField(to="myadmin.subjectlist")),
            ],
        ),
        migrations.CreateModel(
            name="timeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myadmin.day"
                    ),
                ),
            ],
        ),
    ]
