# Generated by Django 4.1.1 on 2022-10-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0014_day_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="class_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myadmin.addclass",
            ),
        ),
    ]
