# Generated by Django 4.1.1 on 2022-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_class_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
