# Generated by Django 4.1.1 on 2022-09-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('leave', models.BooleanField()),
                ('absent', models.BooleanField()),
                ('holiday', models.BooleanField()),
                ('class_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addclass')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.addstudent')),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('class_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addclass')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addexam')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
                ('class_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.addsubject')),
            ],
        ),
    ]
